In [14]:
import pandas as pd
import spacy
from spacy_langdetect import LanguageDetector
from spacy.language import Language

In [ ]:
!pip install spacy-langdetect
!pip install language-tool-python
!pip install langid
!pip install fasttext

In [4]:
df = pd.read_csv('./sample_data/unique_rows.csv')

In [20]:
df.head(10)

,Name_company,Name_company_cleaned,Ticker,Country,Industry,Sector,column1,Country_Language,Language
0,10x Genomics Inc. Class A Common Stock,10x Genomics,NaN,United States,Medical Equipment & Supplies,Health Care,10x genomics,"en, es, de, tl, ca",en
1,1933 Industries Inc,1933 Industries,TGIF,Canada,Biotechnology & Pharmaceuticals,Health Care,1933 industries,"en, fr",en
2,1Life Healthcare Inc,1Life Healthcare,ONEM,United States,Software & IT Services,Technology & Communications,1life healthcare,"en, es, de, tl, ca",en
3,1st Source Corporation Common Stock,1st Source,NaN,United States,Commercial Banks,Financials,1st source,"en, es, de, tl, ca",en
4,"22nd Century Group, Inc.",22nd Century Group,XXII,United States,Tobacco,Food & Beverage,22nd century group,"en, es, de, tl, ca",en
5,2Curex Ab,2Curex,2CUREX,Sweden,Medical Equipment & Supplies,Health Care,2curex,sv,so
6,2seventy bio Inc,2seventy bio,TSVT,United States,Biotechnology & Pharmaceuticals,Health Care,2seventy bio,"en, es, de, tl, ca",en
7,2U Inc. Common Stock,2U,NaN,United States,Software & IT Services,Technology & Communications,2u,"en, es, de, tl, ca",en
8,3D Systems Corporation Common Stock,3D Systems,NaN,United States,Hardware,Technology & Communications,3d systems,"en, es, de, tl, ca",en
9,3i Group PLC,3i Group,TGOPY,United States,Asset Management & Custody Activities,Financials,3i group,"en, es, de, tl, ca",hr

In [12]:
class Name_company_languge_detection:
    def __init__(self):
        self.nlp = spacy.blank('en')
        self.nlp.add_pipe('sentencizer')  # ajout du sentencizer
        @Language.factory('language_detector')
        def create_language_detector(nlp, name):
            return LanguageDetector()
        self.nlp.add_pipe('language_detector', last=True)

    def detect_language(self, text):
        doc = self.nlp(text)
        return doc._.language['language']

In [15]:
lang_detector = Name_company_languge_detection()

In [16]:
df['Language'] = df['Name_company'].apply(lambda x: lang_detector.detect_language(x) if isinstance(x, str) else 'Unknown')

In [ ]:
df

,Name_company,Name_company_cleaned,Ticker,Country,Industry,Sector,column1,Language
0,10x Genomics Inc. Class A Common Stock,10x Genomics,NaN,United States,Medical Equipment & Supplies,Health Care,10x genomics,en
1,1933 Industries Inc,1933 Industries,TGIF,Canada,Biotechnology & Pharmaceuticals,Health Care,1933 industries,en
2,1Life Healthcare Inc,1Life Healthcare,ONEM,United States,Software & IT Services,Technology & Communications,1life healthcare,en
3,1st Source Corporation Common Stock,1st Source,NaN,United States,Commercial Banks,Financials,1st source,en
4,"22nd Century Group, Inc.",22nd Century Group,XXII,United States,Tobacco,Food & Beverage,22nd century group,en
...,...,...,...,...,...,...,...,...
19499,Zymergen Inc,Zymergen,ZY,United States,Chemicals,Resource Transformation,zymergen,de
19500,"Zynerba Pharmaceuticals, Inc.",Zynerba Pharmaceuticals,ZYNE,United States,Biotechnology & Pharmaceuticals,Health Care,zynerba pharmaceuticals,ca
19501,Zynex Inc. Common Stock,Zynex,NaN,United States,Medical Equipment & Supplies,Health Care,zynex,en
19502,Zynga Inc.,Zynga,ZNGA,United States,Software & IT Services,Technology & Communications,zynga,tl
19503,Zynga Inc. Cl A,Zynga,0R0J,United Kingdom,Software & IT Services,Technology & Communications,zynga,tl

In [9]:
country_language_map = {
    'United States': ['en', 'es', 'de', 'tl', 'ca'],
    'Canada': ['en', 'fr'],
    'Sweden': ['sv'],
    'United Kingdom': ['en'],
    'South Africa': ['en', 'af', 'zu', 'xh', 'sw', 'st', 'tn', 'ts', 'ss', 've', 'nr'],
    'Mauritius': ['en', 'fr'],
    'India': ['hi', 'en', 'bn', 'ta', 'te', 'ur', 'gu', 'ml', 'pa', 'or'],
    'British Virgin Islands': ['en'],
    'Italy': ['it'],
    'Australia': ['en'],
    'Cayman Islands': ['en'],
    'Bangladesh': ['bn'],
    'Germany': ['de'],
    'Norway': ['no'],
    'Poland': ['pl'],
    'Japan': ['ja'],
    'Lithuania': ['lt'],
    'Switzerland': ['de', 'fr', 'it', 'rm'],
    'Nigeria': ['en'],
    'France': ['fr'],
    'South Korea': ['ko'],
    'Saudi Arabia': ['ar'],
    'Pakistan': ['ur', 'en'],
    'Thailand': ['th'],
    'Taiwan': ['zh'],
    'Malaysia': ['ms'],
    'Netherlands': ['nl'],
    'Belgium': ['nl', 'fr', 'de'],
    'Philippines': ['fil', 'en'],
    'United Arab Emirates': ['ar'],
    'Singapore': ['en', 'ms', 'ta', 'zh'],
    'Barbados': ['en'],
    'China': ['zh'],
    'Tunisia': ['ar'],
    'Indonesia': ['id'],
    'Colombia': ['es'],
    'Chile': ['es'],
    'Spain': ['es', 'ca', 'eu', 'gl'],
    'Sri Lanka': ['si', 'ta'],
    'Cambodia': ['km'],
    'Russia': ['ru'],
    'Croatia': ['hr'],
    'Luxembourg': ['lb', 'fr', 'de'],
    'Turkey': ['tr'],
    'Peru': ['es'],
    'Hong Kong': ['zh', 'en'],
    'Bulgaria': ['bg'],
    'Brazil': ['pt'],
    'Kazakhstan': ['kk', 'ru'],
    'Greece': ['el'],
    'Finland': ['fi', 'sv'],
    'Morocco': ['ar'],
    'Guernsey': ['en'],
    'Namibia': ['en', 'af'],
    'New Zealand': ['en', 'mi'],
    'Austria': ['de'],
    'Qatar': ['ar'],
    'Oman': ['ar'],
    'Palestinian Territory': ['ar'],
    'Palestine': ['ar'],
    'Slovakia': ['sk'],
    'Serbia and Montenegro': ['sr'],
    'Ireland': ['en', 'ga'],
    'Malawi': ['ny'],
    'Zambia': ['en'],
    'Kuwait': ['ar'],
    'Egypt': ['ar'],
    'Sudan': ['ar'],
    'Bermuda': ['en'],

}

In [10]:
# Créer la nouvelle colonne en mappant les pays aux langues
df['Country_Language'] = df['Country'].apply(lambda x: ', '.join(country_language_map.get(x, [])))

# Afficher le DataFrame avec la nouvelle colonne
df

,Name_company,Name_company_cleaned,Ticker,Country,Industry,Sector,column1,Country_Language
0,10x Genomics Inc. Class A Common Stock,10x Genomics,NaN,United States,Medical Equipment & Supplies,Health Care,10x genomics,"en, es, de, tl, ca"
1,1933 Industries Inc,1933 Industries,TGIF,Canada,Biotechnology & Pharmaceuticals,Health Care,1933 industries,"en, fr"
2,1Life Healthcare Inc,1Life Healthcare,ONEM,United States,Software & IT Services,Technology & Communications,1life healthcare,"en, es, de, tl, ca"
3,1st Source Corporation Common Stock,1st Source,NaN,United States,Commercial Banks,Financials,1st source,"en, es, de, tl, ca"
4,"22nd Century Group, Inc.",22nd Century Group,XXII,United States,Tobacco,Food & Beverage,22nd century group,"en, es, de, tl, ca"
...,...,...,...,...,...,...,...,...
19499,Zymergen Inc,Zymergen,ZY,United States,Chemicals,Resource Transformation,zymergen,"en, es, de, tl, ca"
19500,"Zynerba Pharmaceuticals, Inc.",Zynerba Pharmaceuticals,ZYNE,United States,Biotechnology & Pharmaceuticals,Health Care,zynerba pharmaceuticals,"en, es, de, tl, ca"
19501,Zynex Inc. Common Stock,Zynex,NaN,United States,Medical Equipment & Supplies,Health Care,zynex,"en, es, de, tl, ca"
19502,Zynga Inc.,Zynga,ZNGA,United States,Software & IT Services,Technology & Communications,zynga,"en, es, de, tl, ca"
19503,Zynga Inc. Cl A,Zynga,0R0J,United Kingdom,Software & IT Services,Technology & Communications,zynga,en

In [21]:
def is_language_match(row):
    detected_language = row['Language']
    country_languages = row['Country_Language']
    return detected_language in country_languages

df['Language_Match'] = df.apply(is_language_match, axis=1)
df

,Name_company,Name_company_cleaned,Ticker,Country,Industry,Sector,column1,Country_Language,Language,Language_Match
0,10x Genomics Inc. Class A Common Stock,10x Genomics,NaN,United States,Medical Equipment & Supplies,Health Care,10x genomics,"en, es, de, tl, ca",en,True
1,1933 Industries Inc,1933 Industries,TGIF,Canada,Biotechnology & Pharmaceuticals,Health Care,1933 industries,"en, fr",en,True
2,1Life Healthcare Inc,1Life Healthcare,ONEM,United States,Software & IT Services,Technology & Communications,1life healthcare,"en, es, de, tl, ca",en,True
3,1st Source Corporation Common Stock,1st Source,NaN,United States,Commercial Banks,Financials,1st source,"en, es, de, tl, ca",en,True
4,"22nd Century Group, Inc.",22nd Century Group,XXII,United States,Tobacco,Food & Beverage,22nd century group,"en, es, de, tl, ca",en,True
...,...,...,...,...,...,...,...,...,...,...
19499,Zymergen Inc,Zymergen,ZY,United States,Chemicals,Resource Transformation,zymergen,"en, es, de, tl, ca",de,True
19500,"Zynerba Pharmaceuticals, Inc.",Zynerba Pharmaceuticals,ZYNE,United States,Biotechnology & Pharmaceuticals,Health Care,zynerba pharmaceuticals,"en, es, de, tl, ca",ca,True
19501,Zynex Inc. Common Stock,Zynex,NaN,United States,Medical Equipment & Supplies,Health Care,zynex,"en, es, de, tl, ca",en,True
19502,Zynga Inc.,Zynga,ZNGA,United States,Software & IT Services,Technology & Communications,zynga,"en, es, de, tl, ca",tl,True
19503,Zynga Inc. Cl A,Zynga,0R0J,United Kingdom,Software & IT Services,Technology & Communications,zynga,en,tl,False

In [ ]:
# Étape 1: Extraire toutes les langues uniques de la colonne Language
unique_language = df['Language'].unique()

# Étape 2: Séparation des langues dans Country_Language si elles sont dans une chaîne
df['Country_Language'] = df['Country_Language'].str.split(',')

# Utilisation de explode() pour transformer chaque élément de la liste en ligne
country_languages_series = df['Country_Language'].explode()

# Utilisation de unique() pour obtenir les langues uniques de Country_Language
unique_country_languages = country_languages_series.unique()

# Étape 3: Trouver les différences entre les deux ensembles de langues
languages_not_in_country_languages = set(unique_language) - set(unique_country_languages)

print(languages_not_in_country_languages)

{'Unknown', 'cs', 'af', 'tl', 'cy', 'sl', 'da', 'lv', 'ro', 'sw', 'hu', 'vi', 'ca', 'et', 'sq', 'so'}

# Amelioration de resultat avec **Web Scrapping**

In [24]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://www.esky.fr/guide-de-voyage/volsbillets-davion/informations-douanesvisas/liste-des-langues-officielles-dans-le-monde-entier'
response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

table = soup.find('table')
rows = table.find('tbody').find_all('tr')

data = []
for row in rows:
    cols = row.find_all('td')
    if len(cols) >= 2:
        country = cols[0].text.strip()
        language = cols[1].text.strip()
        data.append((country, language))
df_lang = pd.DataFrame(data, columns=['Country', 'Language'])
df_lang

                  Country                                           Language
0                    Pays                                  Langue officielle
1                 Albanie                                          Albanais,
2                 Aurigny                                           Anglais,
3                 Andorre                                           Catalan,
4                Autriche  Allemand, régionale : Croate du Burgenland et ...
..                    ...                                                ...
254               Ouganda                                  Anglais, Swahili,
255         Côte d'Ivoire                                          Français,
256  Sao Tomé-et-Principe                                         Portugais,
257                Zambie                                           Anglais,
258              Zimbabwe                           Anglais, Shona, Nédébélé

[259 rows x 2 columns]

In [25]:
df_lang.to_csv('df_lang.csv', index=False)
files.download('df_lang.csv')

NameError: ignored

In [22]:
countries = df['Country'].unique()
countries_list = countries.tolist()

In [27]:
filtered_df_lang = df_lang[df_lang['Country'].isin(countries_list)]
filtered_df_lang

           Country                                 Language
16          France                                Français,
26          Jersey             Anglais, Français, Jersiais,
27      Kazakhstan                           Kazakh, Russe,
29   Liechtenstein                                Allemand,
31      Luxembourg     Luxembourgeois , Français, Allemand,
42        Portugal                               Portugais,
68      Bangladesh                                 Bengali,
74     Philippines                        Tagalog, Anglais,
86           Qatar                                   Arabe,
87      Kazakhstan                           Kazakh, Russe,
99            Oman                                   Arabe,
101       Pakistan                         Ourdou, Anglais,
102      Palestine                                   Arabe,
105      Sri Lanka             Cinghalais, Tamoul, Anglais,
114        Vietnam                              Vietnamien,
117       Anguilla                                 Anglais,
120        Bahamas                                 Anglais,
134       Honduras                                Espagnol,
136         Canada                       Anglais, Français,
138     Costa Rica                                Espagnol,
145         Panama                                Espagnol,
172        Uruguay                                Espagnol,
173      Venezuela                                Espagnol,
177           Guam                        Anglais,Chamorro,
208       Botswana                         Anglais, Tswana,
217          Gabon                                Français,
219          Ghana                                 Anglais,
224          Kenya                        Swahili, Anglais,
231         Malawi                           Anglais,Chewa,
239        Nigeria                                 Anglais,
243         Rwanda  Kinyarwanda, Anglais, Français, Swahili
252           Togo                                Français,
258       Zimbabwe                 Anglais, Shona, Nédébélé

In [28]:
country_language_map1 = filtered_df_lang.set_index('Country')['Language'].to_dict()
country_language_map1

{'France': 'Français,',
 'Jersey': 'Anglais, Français, Jersiais,',
 'Kazakhstan': 'Kazakh, Russe,',
 'Liechtenstein': 'Allemand,',
 'Luxembourg': 'Luxembourgeois , Français, Allemand,',
 'Portugal': 'Portugais,',
 'Bangladesh': 'Bengali,',
 'Philippines': 'Tagalog, Anglais,',
 'Qatar': 'Arabe,',
 'Oman': 'Arabe,',
 'Pakistan': 'Ourdou, Anglais,',
 'Palestine': 'Arabe,',
 'Sri Lanka': 'Cinghalais, Tamoul, Anglais,',
 'Vietnam': 'Vietnamien,',
 'Anguilla': 'Anglais,',
 'Bahamas': 'Anglais,',
 'Honduras': 'Espagnol,',
 'Canada': 'Anglais, Français,',
 'Costa Rica': 'Espagnol,',
 'Panama': 'Espagnol,',
 'Uruguay': 'Espagnol,',
 'Venezuela': 'Espagnol,',
 'Guam': 'Anglais,Chamorro,',
 'Botswana': 'Anglais, Tswana,',
 'Gabon': 'Français,',
 'Ghana': 'Anglais,',
 'Kenya': 'Swahili, Anglais,',
 'Malawi': 'Anglais,Chewa,',
 'Nigeria': 'Anglais,',
 'Rwanda': 'Kinyarwanda, Anglais, Français, Swahili',
 'Togo': 'Français,',
 'Zimbabwe': 'Anglais, Shona, Nédébélé'}

In [ ]:
# Dictionnaire des abréviations de langues
language_abbreviations = {
    'Français': 'fr',
    'Anglais': 'en',
    'Jersiais': 'je',
    'Kazakh': 'kk',
    'Russe': 'ru',
    'Allemand': 'de',
    'Luxembourgeois': 'lb',
    'Portugais': 'pt',
    'Bengali': 'bn',
    'Tagalog': 'tl',
    'Arabe': 'ar',
    'Ourdou': 'ur',
    'Cinghalais': 'si',
    'Tamoul': 'ta',
    'Vietnamien': 'vi',
    'Chamorro': 'ch',
    'Espagnol': 'es',
    'Tswana': 'tn',
    'Swahili': 'sw',
    'Chewa': 'ny',
    'Kinyarwanda': 'rw',
    'Shona': 'sn',
    'Nédébélé': 'nd'
}

# Mettre à jour le country_language_map avec les abréviations
for country, languages in country_language_map1.items():
    abbreviated_languages = [language_abbreviations.get(lang.strip(), lang.strip()) for lang in languages.split(',')]
    country_language_map1[country] = ','.join(abbreviated_languages).strip(',')

country_language_map1

{'France': 'fr',
 'Jersey': 'en,fr,je',
 'Kazakhstan': 'kk,ru',
 'Liechtenstein': 'de',
 'Luxembourg': 'lb,fr,de',
 'Portugal': 'pt',
 'Bangladesh': 'bn',
 'Philippines': 'tl,en',
 'Qatar': 'ar',
 'Oman': 'ar',
 'Pakistan': 'ur,en',
 'Palestine': 'ar',
 'Sri Lanka': 'si,ta,en',
 'Vietnam': 'vi',
 'Anguilla': 'en',
 'Bahamas': 'en',
 'Honduras': 'es',
 'Canada': 'en,fr',
 'Costa Rica': 'es',
 'Panama': 'es',
 'Uruguay': 'es',
 'Venezuela': 'es',
 'Guam': 'en,ch',
 'Botswana': 'en,tn',
 'Gabon': 'fr',
 'Ghana': 'en',
 'Kenya': 'sw,en',
 'Malawi': 'en,ny',
 'Nigeria': 'en',
 'Rwanda': 'rw,en,fr,sw',
 'Togo': 'fr',
 'Zimbabwe': 'en,sn,nd'}

In [29]:
# Mettre à jour les valeurs de country_language_map avec celles de country_language_map1
for country in country_language_map:
    if country in country_language_map1:
        country_language_map[country] = country_language_map1[country]

# Afficher le résultat
country_language_map

{'United States': ['en', 'es', 'de', 'tl', 'ca'],
 'Canada': 'Anglais, Français,',
 'Sweden': ['sv'],
 'United Kingdom': ['en'],
 'South Africa': ['en',
  'af',
  'zu',
  'xh',
  'sw',
  'st',
  'tn',
  'ts',
  'ss',
  've',
  'nr'],
 'Mauritius': ['en', 'fr'],
 'India': ['hi', 'en', 'bn', 'ta', 'te', 'ur', 'gu', 'ml', 'pa', 'or'],
 'British Virgin Islands': ['en'],
 'Italy': ['it'],
 'Australia': ['en'],
 'Cayman Islands': ['en'],
 'Bangladesh': 'Bengali,',
 'Germany': ['de'],
 'Norway': ['no'],
 'Poland': ['pl'],
 'Japan': ['ja'],
 'Lithuania': ['lt'],
 'Switzerland': ['de', 'fr', 'it', 'rm'],
 'Nigeria': 'Anglais,',
 'France': 'Français,',
 'South Korea': ['ko'],
 'Saudi Arabia': ['ar'],
 'Pakistan': 'Ourdou, Anglais,',
 'Thailand': ['th'],
 'Taiwan': ['zh'],
 'Malaysia': ['ms'],
 'Netherlands': ['nl'],
 'Belgium': ['nl', 'fr', 'de'],
 'Philippines': 'Tagalog, Anglais,',
 'United Arab Emirates': ['ar'],
 'Singapore': ['en', 'ms', 'ta', 'zh'],
 'Barbados': ['en'],
 'China': ['zh'],
 'Tunisia': ['ar'],
 'Indonesia': ['id'],
 'Colombia': ['es'],
 'Chile': ['es'],
 'Spain': ['es', 'ca', 'eu', 'gl'],
 'Sri Lanka': 'Cinghalais, Tamoul, Anglais,',
 'Cambodia': ['km'],
 'Russia': ['ru'],
 'Croatia': ['hr'],
 'Luxembourg': 'Luxembourgeois , Français, Allemand,',
 'Turkey': ['tr'],
 'Peru': ['es'],
 'Hong Kong': ['zh', 'en'],
 'Bulgaria': ['bg'],
 'Brazil': ['pt'],
 'Kazakhstan': 'Kazakh, Russe,',
 'Greece': ['el'],
 'Finland': ['fi', 'sv'],
 'Morocco': ['ar'],
 'Guernsey': ['en'],
 'Namibia': ['en', 'af'],
 'New Zealand': ['en', 'mi'],
 'Austria': ['de'],
 'Qatar': 'Arabe,',
 'Oman': 'Arabe,',
 'Palestinian Territory': ['ar'],
 'Palestine': 'Arabe,',
 'Slovakia': ['sk'],
 'Serbia and Montenegro': ['sr'],
 'Ireland': ['en', 'ga'],
 'Malawi': 'Anglais,Chewa,',
 'Zambia': ['en'],
 'Kuwait': ['ar'],
 'Egypt': ['ar'],
 'Sudan': ['ar'],
 'Bermuda': ['en']}

In [30]:
for country, language in country_language_map.items():
    if not isinstance(language, list):
        country_language_map[country] = [language]

# Afficher le résultat
country_language_map

{'United States': ['en', 'es', 'de', 'tl', 'ca'],
 'Canada': ['Anglais, Français,'],
 'Sweden': ['sv'],
 'United Kingdom': ['en'],
 'South Africa': ['en',
  'af',
  'zu',
  'xh',
  'sw',
  'st',
  'tn',
  'ts',
  'ss',
  've',
  'nr'],
 'Mauritius': ['en', 'fr'],
 'India': ['hi', 'en', 'bn', 'ta', 'te', 'ur', 'gu', 'ml', 'pa', 'or'],
 'British Virgin Islands': ['en'],
 'Italy': ['it'],
 'Australia': ['en'],
 'Cayman Islands': ['en'],
 'Bangladesh': ['Bengali,'],
 'Germany': ['de'],
 'Norway': ['no'],
 'Poland': ['pl'],
 'Japan': ['ja'],
 'Lithuania': ['lt'],
 'Switzerland': ['de', 'fr', 'it', 'rm'],
 'Nigeria': ['Anglais,'],
 'France': ['Français,'],
 'South Korea': ['ko'],
 'Saudi Arabia': ['ar'],
 'Pakistan': ['Ourdou, Anglais,'],
 'Thailand': ['th'],
 'Taiwan': ['zh'],
 'Malaysia': ['ms'],
 'Netherlands': ['nl'],
 'Belgium': ['nl', 'fr', 'de'],
 'Philippines': ['Tagalog, Anglais,'],
 'United Arab Emirates': ['ar'],
 'Singapore': ['en', 'ms', 'ta', 'zh'],
 'Barbados': ['en'],
 'China': ['zh'],
 'Tunisia': ['ar'],
 'Indonesia': ['id'],
 'Colombia': ['es'],
 'Chile': ['es'],
 'Spain': ['es', 'ca', 'eu', 'gl'],
 'Sri Lanka': ['Cinghalais, Tamoul, Anglais,'],
 'Cambodia': ['km'],
 'Russia': ['ru'],
 'Croatia': ['hr'],
 'Luxembourg': ['Luxembourgeois , Français, Allemand,'],
 'Turkey': ['tr'],
 'Peru': ['es'],
 'Hong Kong': ['zh', 'en'],
 'Bulgaria': ['bg'],
 'Brazil': ['pt'],
 'Kazakhstan': ['Kazakh, Russe,'],
 'Greece': ['el'],
 'Finland': ['fi', 'sv'],
 'Morocco': ['ar'],
 'Guernsey': ['en'],
 'Namibia': ['en', 'af'],
 'New Zealand': ['en', 'mi'],
 'Austria': ['de'],
 'Qatar': ['Arabe,'],
 'Oman': ['Arabe,'],
 'Palestinian Territory': ['ar'],
 'Palestine': ['Arabe,'],
 'Slovakia': ['sk'],
 'Serbia and Montenegro': ['sr'],
 'Ireland': ['en', 'ga'],
 'Malawi': ['Anglais,Chewa,'],
 'Zambia': ['en'],
 'Kuwait': ['ar'],
 'Egypt': ['ar'],
 'Sudan': ['ar'],
 'Bermuda': ['en']}

In [31]:
 from google.colab import files

df.to_csv('name_language.csv', index=False)
files.download('name_language.csv')

## ---------------------------------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
df = pd.read_csv('./sample_data/unique_rows.csv')

# **langdetect**

In [35]:
from langdetect import detect

def detect_lang_langdetect(text):
    try:
        return detect(text)
    except:
        return 'unknown'

df['langdetect'] = df['Name_company'].apply(detect_lang_langdetect)
df.to_csv('name_language_langdetect.csv', index=False)

## **langid**

In [34]:
  import langid

def detect_lang_langid(text):
    try:
        lang, _ = langid.classify(text)
        return lang
    except:
        return 'unknown'

df['langid'] = df['Name_company'].apply(detect_lang_langid)
df.to_csv('name_language_langid.csv', index=False)